### PR TITLE
Optimized ray function

### PR DESCRIPTION
**Pull request by Diazepawn**
Ray function used 8 steps to iterator over the board, only 7 were necessary.

### CODE REVIEW

**Comment by kz04px** [comment]
Since fate has decided this should increase the file size, let's keep it around for potential future use. Thanks.

**Comment by gcp** [comment]
It may be an Elogainer, as this is very perf critical (and it has dependencies so it doesn't pipeline on the CPU).

**Comment by gcp** [comment]
Running as http://chess.grantnet.us/test/30422

**Comment by gcp** [comment]
```
ELO   | 11.38 +- 7.04 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 5344 W: 1617 L: 1442 D: 2285
```

About 3 Elo per byte, not bad. I think we should merge.

**Comment by kz04px** [comment]
The Fates are kind. Thanks.

**Pull request merged**
