### PR TITLE
Make stop a single integer.

### PR DESCRIPTION
**Pull request by gcp**
There's no need for this to be an array (they're in the same cacheline anyway!).

### CODE REVIEW

**Comment by gcp** [comment]
@GediminasMasaitis what do you think? Do we need this tested on OB?

**Comment by GediminasMasaitis** [comment]
> @GediminasMasaitis what do you think? Do we need this tested on OB?

I'm not well versed on how exactly the CPU caching works, but in my head I was just thinking "don't access the same address from multiple threads to reduce memory contention".

On OB the SMP tests are 8 threads, I think. I suppose that's fine to verify that it doesn't slow down. I also left a 12T vs 12T test of this while I'm off to work.

**Comment by gcp** [comment]
>I'm not well versed on how exactly the CPU caching works, but in my head I was just thinking "don't access the same address from multiple threads to reduce memory contention".

I think this is an issue if the data is changed, so the various CPUs need to send cache coherency exchanges to invalidate each others' cached data. But the ```stop``` flag doesn't change during the search so no data would be exchanged, they'll get the right value in their cache on the first lookup and that's it. It would be different if these were for example node counters.

The original version doesn't insert any padding in between the flags, so they're all in the same cacheline, which means it could never prevent this from happening anyway.

(Also given that this is not an atomic none of this is actually guaranteed to work at all, but it clearly does so we can ignore that on x86)

**Comment by GediminasMasaitis** [comment]
UHO book, 1+0.01 12T vs 12T
```
Score of 4ku vs 4ku-master: 3657 - 3523 - 4370  [0.506] 11550
...      4ku playing White: 2400 - 1229 - 2146  [0.601] 5775
...      4ku playing Black: 1257 - 2294 - 2224  [0.410] 5775
...      White vs Black: 4694 - 2486 - 4370  [0.596] 11550
Elo difference: 4.0 +/- 5.0, LOS: 94.3 %, DrawRatio: 37.8 %
```

Looks like it's safe to do

**Comment by GediminasMasaitis** [comment]
Thanks!

**Pull request merged**
