### PR TITLE
Forward futility pruning.

### PR DESCRIPTION
**Pull request by gcp**
```
ELO   | 7.34 +- 5.35 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=64MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 9800 W: 3073 L: 2866 D: 3861
```

### CODE REVIEW

**Comment by kz04px** [comment]
Thanks.

**Comment by tissatussa** [comment]
regarding #73 i see this code part :


```cpp
if (in_qsearch && !in_check && static_eval + 50 + max_material[piece_on(pos, move.to)] < alpha {
  best_score = alpha;
  break;
} else if (!in_qsearch && !in_check && !(move == tt_move) &&
           static_eval + 150 * depth + max_material[piece_on(pos, move.to)] < alpha) {
  best_score = alpha;
  break;
}
```

how are the numbers '50' and '150' determined ?
it's all done by self-play tests ?

**Comment by gcp** [comment]
Guessing, quick tests, and whatever doesn't use much bytes.

**Comment by tissatussa** [comment]
OK .. and i asked this question before : are any test positions involved ? I mean, 50 could be 100 and 150 could be 250 .. or did you rely on other engines / code ?

**Comment by gcp** [comment]
Test positions are useless, I never use them. Just play fast games.

**Comment by gcp** [comment]
The delta margin has to be on the order of the largest expected positional jumps - but there's no reason why it has to be correct. The CPW recommends 2 pawns but 4ku has so little eval factors something much smaller is fine. The other margin has to follow the "reverse" futility pruning, but maybe with some extra margin as it doesn't know if the move is a check yet. But again, that's the theory, put whatever value works.

_Neither of them was actually tuned_, so there may be more Elo here. Just try halving and doubling the values (or plus 50% and minus 33%) and see what happens to the Elo. I spent most of my time when trying to get this to work to understand why I couldn't ```break``` the loop as the moves are in MVV/LVA order so it should be equivalent to ```continue```. It was because I forgot that the TT move can be not-a-capture, hence the additional condition there.

**Pull request merged**
